### PR TITLE
Completed Dp-2

### PR DESCRIPTION
**Pull request by svyas97**
Please check the TC and SC, I think it might be wrong

### CODE REVIEW

**Review by nsibal — COMMENTED** [review]
Please fix the indentation of the code. Also, just by looking at the first few lines, I think your code won't execute because `j` isn't defined before L3 in both the files.

**Comment by nsibal** [comment]
Please fix the indentation of the code. Also, just by looking at the first few lines, I think your code won't execute because `j` isn't defined before L3 in both the files.

**Comment by svyas97** [comment]
> Please fix the indentation of the code. Also, just by looking at the first few lines, I think your code won't execute because `j` isn't defined before L3 in both the files.

Hi Nirbhay, looks like the file has some issues, I will create a new pull request.

**Comment by svyas97** [comment]
Created a new pull request

**Pull request closed without merging**
